name: pylipd
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.12
  - pytest
  - pandas
  - pip:
    - bibtexparser
    - rdflib
    - pybtex
    - bagit
    - tqdm
    - doi2bib
    - '-e .'

